name: Build Pikafish XQ Rules

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      ARCH: x86-64-universal
      COMP: clang
    steps:
      - uses: actions/checkout@v4

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          install: mingw-w64-clang-x86_64-clang make git

      - name: Apply XQ rule patch
        shell: msys2 {0}
        run: |
          sed -i 's/\r$//' xq-rule.patch
          git apply --verbose xq-rule.patch

      - name: Build
        working-directory: src
        shell: msys2 {0}
        run: make -j4 build EXE=pikafish-master.exe

      - name: Strip
        working-directory: src
        shell: msys2 {0}
        run: make strip EXE=pikafish-master.exe

      - uses: actions/upload-artifact@v4
        with:
          name: Pikafish-XQ-Windows-x86-64-universal
          path: src/pikafish-master.exe
